@startuml

interface IStack<T>{
    +push(item:T)
    +pop():T
    +peek():T
}

class LinkedListStack<T>{
    -Collection: T[]
    --
    +push(item:T)
    +pop():T
    +peek():T
}

class ListStack<T>{
    -Collection: T[]
    --
    +push(item:T)
    +pop():T
    +peek():T
}

class Stack<T>{
    -stack:IStack[]
    +push(item:T)
    +pop():T
    +peek():T
}
 
LinkedListStack -.l-|> IStack : <<implements>>
ListStack -.r-|> IStack : <<implements>>
Stack -.d-|> IStack : <<implements>>

hide empty members
@enduml