@startuml
title Vehicle

class Vehicle{
    -manufacturer:String
    -year:int
    -color:String
    --
    +Start()
    +Drive()
    +Stop()
}

class Car extends Vehicle{
    +OpenSunRoof()
}

class Truck extends Vehicle{
    +Transport()
}

class Bus extends Vehicle{
    +Scheduling()
}

class SchoolBus extends Bus{
    +GetFare()
}

hide empty member
@enduml