@startuml
title Vehicle

class Vehicle{
    #manufacturer:String
    #year:int
    #color:String
    --
    +getManufacturer():void
    +getYear():void
    +getColor():void
    +setManufacturer():void
    +setYear():void
    +setColor():void
    --
    +Vehicle()
    +Vehicle(manufacturer:string, year:int, color:string)
    --
    +Start():void
    +Drive():void
    +Stop():void
    +toString():string
}

class Car extends Vehicle{
    +OpenSunRoof()
}

class Truck extends Vehicle{
    +Transport()
}

class Bus extends Vehicle{
    +Scheduling()
}

class SchoolBus extends Bus{
    +GetFare()
}

hide empty member
@enduml